### ISSUE TITLE
Feature request: account name in contacts apps

### ISSUE THREAD

**Issue by FGIKCM** [messageconcept/PeopleSyncClient#1]
Hello,

On your (great) app, we can add 2 accounts, and specify a name for each.
But on the Contacts app, we only see 2 accounts named "PeopleSync". It would be great if this could be customized to have the name we entered for each account :)

This is the only annoying point I found. Your app is just perfect, works out of the box, and offers easy debug information. Great job, thanks!

**Comment by mbiebl** [comment]
Thanks for your feedback.
Which contacts app do you use?
Can you attach a screenshot, please.

**Comment by FGIKCM** [comment]
Hello,

I use the default contact apps from Samsung (on Galaxy S10 - Android 10)

here are the screen captures:

PeopleSync accounts:
https://drive.google.com/file/d/1dwsy1eHrVwQ-e1JhpXevvKy6MdOmf0mo

Result in Contacts app:
https://drive.google.com/file/d/1kjo2WEApd2xG3E7Ckhqn6AP7O_twG17k

**Comment by mbiebl** [comment]
Hm, that seems to be a Samsung specific issue.
Here is, how it looks like on a Android 10 device using the AOSP contacts app and the Google contacts app. I have two accounts: john (2 addressbooks) and lisa (1 addressbook)

![Screenshot_1579538880](https://user-images.githubusercontent.com/3609611/72744608-2b002700-3bae-11ea-855f-d75fde80ad7a.png)

AOSP contacts app
![Screenshot_1579539098](https://user-images.githubusercontent.com/3609611/72744623-33f0f880-3bae-11ea-8adc-98697227cc2b.png)

Google Contacts app
https://play.google.com/store/apps/details?id=com.google.android.contacts
![Screenshot_1579539129](https://user-images.githubusercontent.com/3609611/72744657-453a0500-3bae-11ea-9c38-c4ca649024b6.png)

So, I'm not sure if we can do anything about that and this rather seems to be a Samsung/One UI issue to me.

**Comment by FGIKCM** [comment]
ah ok, looks like you are right. Thanks. I will try the Google contact app, and deploy it on our MDM if it works. 

Thanks a lot.
