### ISSUE TITLE
APK available?

### ISSUE THREAD

**Issue by IzzySoft** [messageconcept/PeopleSyncClient#2]
With your app being FOSS and free of proprietary components (as far as I can see), would you consider also providing it outside Google's walled gardens – e.g. by attaching it to your "tagged releases" here?

**Comment by mbiebl** [comment]
since the PeopleSyncClient app is based on DAVx5 tailored to our specific
needs, I usually recommend that you should use DAVx5 directly instead.
They do provide APKs e.g. via
https://f-droid.org/de/packages/at.bitfire.davdroid/ but you can also
support them by buying the app via Google Play.

**Comment by IzzySoft** [comment]
Ah, didn't know that your app is based on this. So all fine; I was just thinking you might want yours to be "openly available" as well. Thanks for your prompt answer!
